name: python 3.6
channels:
  - conda-forge
dependencies:
  - python=3.6
  - numpy=1.18.5
  - pyomo=5.7.3
  - glpk
  - matplotlib=3.2.2
  - plotly=5.16.1
  - scipy
#  - ipympl=0.9.3
  - pip:
    - nbimporter==0.3.4
    - ipywidgets==7.7.2
#control==0.9.4
#mplcursors==0.5.2